import "@shared/css/globals.css";
import { Noto_Sans } from "next/font/google";

import QueryProvider from "@shared/components/contexts/query-provider";
import PageWrapper from "@shared/components/extends/page-wrapper";
import { Toaster } from "@shared/components/ui/toaster";
import { AuthActivityProvider } from "@shared/components/contexts/auth-activity-provider";

import type { Metadata } from "next";

const font = Noto_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} antialiased`}>
        <QueryProvider>
          <AuthActivityProvider>
            <PageWrapper>{children}</PageWrapper>
            <Toaster />
          </AuthActivityProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
