import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import PageWrapper from "@/components/extends/page-wrapper";
import QueryProvider from "@/contexts/query-provider";

const font = Noto_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} antialiased`}>
        <QueryProvider>
          <PageWrapper>{children}</PageWrapper>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
